# Generated by Django 3.2.16 on 2023-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'left'), (1, 'right')], default=1, null=True),
        ),
    ]
