# Generated by Django 3.2.16 on 2023-01-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_book_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'left'), (1, 'right')], null=True),
        ),
    ]
